GET http://localhost:3000/recipes.json

###
POST http://localhost:3000/recipes.json
content-type: application/json

{
  "name": "Bread",
  "ingredients": "water, flour, oil",
  "description": "one of the most versatile foods",
  "cook_time": "300"
}

###
GET http://localhost:3000/recipes/52

###
PATCH http://localhost:3000/recipes/50
content-type: application/json

{
  "name": "Bread",
  "ingredients": "water + flour",
  "description": "one of the most versatile foods",
  "cook_time": "300"
}

###
DELETE http://localhost:3000/recipes/51